# Generated by Django 4.0.4 on 2022-05-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_senior_dev',
            field=models.BooleanField(default=False, verbose_name='senior dev status'),
        ),
    ]
